apiVersion: v1
kind: "Template"
metadata:
  name: apiman-dev-local-build-template
  annotations:
    description: |
      Template for creating local builds of apiman components from local
      source.
    tags: "infrastructure"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-deployer
    name: apiman-deployer
    annotations:
      openshift.io/image.insecureRepository: ${INSECURE_REPOSITORY}
  spec:
    dockerImageRepository: ${IMAGE_PREFIX}apiman-deployer
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-elasticsearch
    name: apiman-elasticsearch
    annotations:
      openshift.io/image.insecureRepository: ${INSECURE_REPOSITORY}
  spec:
    dockerImageRepository: ${IMAGE_PREFIX}apiman-elasticsearch
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-curator
    name: apiman-curator
    annotations:
      openshift.io/image.insecureRepository: ${INSECURE_REPOSITORY}
  spec:
    dockerImageRepository: ${IMAGE_PREFIX}apiman-curator
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-deployer
    name: apiman-deployer
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-deployer:latest
    resources: {}
    source:
      contextDir: deployer
      git:
        uri: https://github.com/openshift/origin-apiman
        ref: master
      type: Git
    strategy:
      type: Docker
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: apiman-elasticsearch
    name: apiman-elasticsearch
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-elasticsearch:latest
    resources: {}
    source:
      contextDir: deployer/common/elasticsearch
      git:
        uri: https://github.com/openshift/origin-apiman
        ref: master
      type: Git
    strategy:
      type: Docker
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-curator
    name: apiman-curator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-curator:latest
    resources: {}
    source:
      contextDir: deployer/common/curator
      git:
        uri: https://github.com/openshift/origin-apiman
        ref: master
      type: Git
    strategy:
      type: Docker
parameters:
-
  name: IMAGE_PREFIX
-
  name: INSECURE_REPOSITORY
  value: "false"
