apiVersion: "v1"
kind: "List"
items:
-
  apiVersion: "v1"
  kind: "Template"
  metadata:
    name: apiman-deployer-account-template
    annotations:
      description: "Template for creating the service accounts needed for the APIMan deployer."
      tags: "infrastructure"
    labels:
      apiman-infra: support
  objects:
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: apiman-deployer
  -
    apiVersion: v1
    kind: RoleBinding
    metadata:
      name: apiman-deployer-edit-role
    roleRef:
      kind: ClusterRole
      name: edit
    subjects:
    - kind: ServiceAccount
      name: apiman-deployer
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: apiman-elasticsearch
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: apiman-curator
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: apiman-gateway
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: apiman-console
-
  apiVersion: "v1"
  kind: "Template"
  metadata:
    name: apiman-deployer-template
    annotations:
      description: "Template for running the APIMan deployer in a pod. Requires empowered 'apiman-deployer' service account and 'apiman-deployer' secret."
      tags: "infrastructure"
  labels:
    provider: openshift
    component: deployer
  objects:
  -
    apiVersion: v1
    kind: Pod
    metadata:
      generateName: apiman-deployer-
    spec:
      containers:
      - image: ${IMAGE_PREFIX}apiman-deployer:${IMAGE_VERSION}
        imagePullPolicy: IfNotPresent
        name: deployer
        volumeMounts:
        - name: empty
          mountPath: /etc/deploy
        env:
          - name: PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: IMAGE_PREFIX
            value: ${IMAGE_PREFIX}
          - name: IMAGE_VERSION
            value: ${IMAGE_VERSION}
          - name: MODE
            value: ${MODE}
          - name: IGNORE_PREFLIGHT
            value: ${IGNORE_PREFLIGHT}
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: apiman-deployer
      volumes:
      - name: empty
        emptyDir: {}
  parameters:
  -
    description: 'Specify prefix for apiman components; e.g. for "openshift/origin-apiman-deployer:v1.1", set prefix "openshift/origin-"'
    name: IMAGE_PREFIX
    value: "docker.io/openshift/origin-"
  -
    description: 'Specify version for apiman components; e.g. for "openshift/origin-apiman-deployer:v1.1", set version "v1.1"'
    name: IMAGE_VERSION
    value: "latest"
  -
    description: "The mode that the deployer runs in: one of install|reinstall|uninstall."
    name: MODE
    value: "install"
  -
    description: "Continue deploying even if the preflight validation fails."
    name: IGNORE_PREFLIGHT
    value: "false"
